### ISSUE TITLE
weex-advanced 库废弃

### ISSUE THREAD

**Issue by walid1992** [joggerplus/awesome-weex#3]
您好，我是weex-advanced demo的贡献者，这个库是.we后缀文件开发的，最新基于vue2.0我写了一个新的frame集成了android、ios、web三端，并且封装了一个组件、API等，希望将我的新库加入进来，谢谢~
项目地址：https://github.com/osmartian/weex-frame

**Comment by coderyi** [comment]
非常谢谢的通知，已经移除weex-advanced ，并且加入了weex-frame,感谢你为weex又开源了一个新库

**Comment by walid1992** [comment]
👌
